ccflags-y += -Idrivers/media/platform/msm/camera_v2
ccflags-y += -Idrivers/media/platform/msm/camera_v2/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2/sensor/cci
obj-$(CONFIG_MSMB_CAMERA) += msm_ois_lc898122.o
obj-$(CONFIG_MSMB_CAMERA) += OisCmd_lc898122.o
obj-$(CONFIG_MSMB_CAMERA) += OisIni_lc898122.o
